### ISSUE TITLE
SSR example

### ISSUE THREAD

**Issue by dmitrika** [ratson/react-head-tags#1]
Hi, thanks for the library!

I tried to use it with SSR `renderToNodeStream` function, but it doesn't work as expected. I got html without tags and they coming only after client render.

As far as I know, until we call `stream.pipe(res, { end: false })` nothing is rendered, so no meta info is received. But when we start piping, we cant modify head. Is that correct?

In tests, I see, that you use streamToPromise. Why? Is it required, so HeadManager would be able to collect all tags?

**Comment by ratson** [comment]
@dmitrika I have added a test to show [how to work with stream](https://github.com/ratson/react-head-tags/blob/f24e760f421123412215d6063e606551797d5456/src/index.test.js#L158-L202).

`streamToPromise` is used to `await` for the rendering, so head tags are collected. You could listen to stream finish event too.

**Comment by dmitrika** [comment]
Thanks, that's a perfect example!
